version: '3.8'

services:
  backend:
    build: ./legalaidnow-backend
    container_name: legalaidnow-spring-backend
    ports:
      - "9091:8081"
    environment:
      SPRING_APPLICATION_NAME: legalaidnow-backend
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/legalaidnow_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: '@diPostgresSQL'
      JPA_HIBERNATE_DDL_AUTO: update
      JPA_SHOW_SQL: "true"
      JPA_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - legalaidnow-net
    restart: unless-stopped

  frontend:
    build: ./legalaidnow-frontend
    container_name: legalaidnow-react-frontend
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - legalaidnow-net
    restart: unless-stopped

networks:
  legalaidnow-net:
    driver: bridge
