services:
  backend:
    build:
      context: ./legalaidnow-backend
      dockerfile: Dockerfile
    container_name: legalaidnow-spring-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - legalaid-net

  frontend:
    build:
      context: ./legalaidnow-frontend
      dockerfile: Dockerfile
    container_name: legalaidnow-react-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - legalaid-net

networks:
  legalaid-net: