spring.application.name=legalaidnow-backend

# --- MySQL Database Connection (Local) ---
spring.datasource.url=jdbc:mysql://localhost:3306/legalaid_db
spring.datasource.username=root
spring.datasource.password=@diMySQL

# --- JPA / Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
