# --- MySQL Database Connection (Docker Compose) ---
# spring.datasource.url=jdbc:mysql://mysql-db:3306/legalaid_db
# spring.datasource.username=root
# spring.datasource.password=@diMySQL

# --- JPA / Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true