name: CI - Build & Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Set up Java (for backend)
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 3. Build backend
    - name: Build Backend (Spring Boot)
      working-directory: ./backend
      run: mvn clean package -DskipTests

    # 4. Set up Node.js (for frontend)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 5. Build frontend
    - name: Build Frontend (React)
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    # 6. Build Docker images
    - name: Build Docker Images
      run: |
        docker build -t my-backend:latest ./backend
        docker build -t my-frontend:latest ./frontend
